### ISSUE TITLE
Optimize the filter and mode functions

### ISSUE THREAD

**Issue by eltharim** [Hypothesize/standard.js#22]
The lib is already pretty optimized, but it needs further checking to further optimize performance and ensure all algorithms are the most efficient according to industry best practice.

**Comment by eltharim** [comment]
The Datatable "filter" function should be updated so that the statistics needed for outliers filtering are calculated only once, not once per value to be filtered.

**Comment by MarissaRodenburg** [comment]
The mode function also needs to be optimized to run over a sorted array, reducing the mode calculation to O(n)

**Comment by MarissaRodenburg** [comment]
Add unit tests for variance and deviation
